image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build
            caches:
              - node
            script:
              - npm install
              - npm run build
        - step:
            name: Code Linting
            script:
              - npm install eslint
              - npx eslint --ext .vue,.js,.jsx,.cjs,.mjs .
            caches:
              - node

definitions:
  caches:
    node: node_modules

options:
  max-time: 10

