image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build
            caches:
              - node
            script:
              - npm install
              - npm run build
definitions:
  caches:
    node: node_modules

options:
  max-time: 10

